import Image from 'next/image';
import kingpng from './king.png';
import clipboard from './clipboard.png';
import googledrive from './google-drive.png';

import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

import creds from '../assets/senior-mania-svc-creds.json';
import { LeaderboardEntry } from '@/components/LeaderboardEntry';

export type TeamEntry = {
  teamName: string,
  points: number
}


export default function LeaderBoard( { teams }: { teams: TeamEntry[] }) {
    if(!teams[0]) return (<div>Loading...</div>);

    return (
        <div className="main">
            <div className='header'>
                <div className='title-container'>
                    <h1 className="text-center w-full bg-pink-200">SENIOR MANIA LEADERBOARD</h1>
                </div>
                <a href="https://drive.google.com/drive/u/1/folders/1UJnDfbiGWN_08yGfCraG97LZAAqDwqfd" className="challenges-button">
                    <Image 
                        src={googledrive}
                        alt="Go to Challenges" 
                    />
                </a>
            </div>


            <div className='podium'>
                <div className='second-place'>
                    <h1 className="name">{teams[1].teamName}</h1>
                    <h2 className="score" style={{ color: "#e6e8fa" }}>{teams[1].points}</h2>
                </div>
                <div className='first-place'>
                    <Image 
                        src={kingpng}
                        alt=''
                        width={50}
                        height={50}
                    />
                    <h1 className="name">{teams[0].teamName}</h1>
                    <h2 className="score" style={{ color: "#ffd700" }}>{teams[0].points}</h2>
                </div>
                <div className='third-place'>
                    <h1 className="name">{teams[2].teamName}</h1>
                    <h2 className="score" style={{ color: "#cd7f32" }}>{teams[2].points}</h2>
                </div>
            </div>

            <div className='leaderboard'>
                {teams.slice(3).map((user, idx) => (
                    <LeaderboardEntry key={idx} team={user} idx={idx} />
                ))}
            </div>
        </div>
    );
};

export async function getServerSideProps() { 
    const serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: creds.client_email,
        key: creds.private_key,
        scopes: [
            'https://www.googleapis.com/auth/spreadsheets',
        ],
    });

    const doc = new GoogleSpreadsheet('1xCXQvmwsHsqPLKhehIpf8an3NUlKT3obWrcEON_0gjA', serviceAccountAuth);
    await doc.loadInfo(); // loads document properties and worksheets
    // console.log(doc.sheetCount);
    // console.log(doc.title);

    const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
    const rows = (await sheet.getRows({offset: 1}));

    let teamPoints: TeamEntry[] = [];

    rows.map((row) => {
    teamPoints.push({teamName: row.get('Team Name'), points: row.get('POINTS')});
    })

    let teams = teamPoints.sort((a, b) => b.points - a.points);
    return { 
        props: { teams }, 
    }; 
}